-- MySQL Script generated by MySQL Workbench
-- Wed Feb 14 22:54:18 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema fddLibrary
-- -----------------------------------------------------
-- database for fdd library managment.

-- -----------------------------------------------------
-- Schema fddLibrary
--
-- database for fdd library managment.
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `fddLibrary` DEFAULT CHARACTER SET gbk ;
USE `fddLibrary` ;

-- -----------------------------------------------------
-- Table `fddLibrary`.`AdminInfo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fddLibrary`.`AdminInfo` (
  `admin_id` VARCHAR(20) NOT NULL DEFAULT 'root',
  `admin_pw` VARCHAR(45) NOT NULL DEFAULT '123456',
  PRIMARY KEY (`admin_id`),
  UNIQUE INDEX `admin_id_UNIQUE` (`admin_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fddLibrary`.`BookInfo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fddLibrary`.`BookInfo` (
  `book_id` INT UNSIGNED NOT NULL,
  `book_name` VARCHAR(45) NOT NULL,
  `book_isbn` VARCHAR(20) NOT NULL,
  `book_cg` VARCHAR(10) NOT NULL COMMENT 'book category.',
  `book_pos` VARCHAR(45) NOT NULL COMMENT 'book position',
  `book_pre` VARCHAR(20) NOT NULL COMMENT 'book press',
  `book_status` TINYINT NOT NULL DEFAULT 1,
  `book_Url` VARCHAR(45) NULL,
  PRIMARY KEY (`book_id`),
  UNIQUE INDEX `book_id_UNIQUE` (`book_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fddLibrary`.`UserInfo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fddLibrary`.`UserInfo` (
  `user_id` VARCHAR(15) NOT NULL,
  `user_name` VARCHAR(20) NOT NULL,
  `user_pw` VARCHAR(45) NOT NULL,
  `user_headUrl` VARCHAR(45) NULL,
  `user_salt` VARCHAR(10) NULL,
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX `user_id_UNIQUE` (`user_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fddLibrary`.`LoanRelation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fddLibrary`.`LoanRelation` (
  `loan_time` DATE NOT NULL,
  `book_id` INT UNSIGNED NOT NULL,
  `user_id` VARCHAR(15) NOT NULL,
  `return_time` DATE NOT NULL,
  `return_status` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`loan_time`, `book_id`, `user_id`),
  INDEX `book_id` (`book_id` ASC),
  INDEX `user_id` (`user_id` ASC),
  CONSTRAINT `book_id`
    FOREIGN KEY (`book_id`)
    REFERENCES `fddLibrary`.`BookInfo` (`book_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `fddLibrary`.`UserInfo` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
