-- MySQL Script generated by MySQL Workbench
-- Tue Mar  6 20:02:42 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema fddLibrary
-- -----------------------------------------------------
-- database for fdd library managment.

-- -----------------------------------------------------
-- Schema fddLibrary
--
-- database for fdd library managment.
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `fddLibrary` DEFAULT CHARACTER SET gbk ;
USE `fddLibrary` ;

-- -----------------------------------------------------
-- Table `fddLibrary`.`AdminInfo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fddLibrary`.`AdminInfo` (
  `admin_id` VARCHAR(20) NOT NULL DEFAULT 'admin',
  `admin_pw` VARCHAR(45) NOT NULL DEFAULT '123;',
  PRIMARY KEY (`admin_id`),
  UNIQUE INDEX `admin_id_UNIQUE` (`admin_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fddLibrary`.`BookInfo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fddLibrary`.`BookInfo` (
  `book_id` INT UNSIGNED NOT NULL,
  `book_name` VARCHAR(45) NOT NULL DEFAULT '',
  `book_author` VARCHAR(45) NOT NULL DEFAULT '',
  `book_isbn` VARCHAR(20) NOT NULL DEFAULT '',
  `book_cg` VARCHAR(10) NOT NULL DEFAULT '' COMMENT 'book category.',
  `book_pos` VARCHAR(45) NOT NULL DEFAULT '' COMMENT 'book position',
  `book_pre` VARCHAR(20) NOT NULL DEFAULT '' COMMENT 'book press',
  `book_status` TINYINT NOT NULL DEFAULT 1,
  `book_del` TINYINT NOT NULL DEFAULT 0,
  `book_Url` VARCHAR(45) NULL DEFAULT '',
  PRIMARY KEY (`book_id`),
  UNIQUE INDEX `book_id_UNIQUE` (`book_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fddLibrary`.`UserInfo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fddLibrary`.`UserInfo` (
  `user_id` VARCHAR(15) NOT NULL,
  `user_name` VARCHAR(20) NOT NULL DEFAULT '',
  `user_pw` VARCHAR(45) NOT NULL DEFAULT '',
  `user_salt` VARCHAR(10) NULL DEFAULT '',
  `user_headUrl` VARCHAR(45) NULL DEFAULT '',
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX `user_id_UNIQUE` (`user_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fddLibrary`.`LoanRelation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fddLibrary`.`LoanRelation` (
  `loan_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `book_id` INT UNSIGNED NOT NULL,
  `user_id` VARCHAR(15) NOT NULL,
  `loan_time` DATE NOT NULL,
  `return_time` DATE NOT NULL,
  `loan_finish` TINYINT NOT NULL DEFAULT 0,
  INDEX `book_id` (`book_id` ASC),
  INDEX `user_id` (`user_id` ASC),
  PRIMARY KEY (`loan_id`),
  UNIQUE INDEX `loan_id_UNIQUE` (`loan_id` ASC),
  CONSTRAINT `book_id`
    FOREIGN KEY (`book_id`)
    REFERENCES `fddLibrary`.`BookInfo` (`book_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `fddLibrary`.`UserInfo` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
